name: Manual Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to push the tag'
        required: true
        type: choice
        options:
          - main
          - feature

jobs:
  tag-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Git
      run: |
        git config user.name "vjraghav55"
        git config user.email "vjraghav55@gmail.com"

    - name: Get latest tag
      id: get-latest-tag
      run: |
        latest_tag=$(git tag --list 'uat_v*' | sort -V | tail -n 1)
        echo "Latest tag: $latest_tag"
        echo "::set-output name=tag::$latest_tag"

    - name: Calculate next tag
      id: calculate-next-tag
      run: |
        latest_tag=${{ steps.get-latest-tag.outputs.tag }}
        if [ -z "$latest_tag" ]; then
          echo "No existing tags found with prefix 'uat_v'. Exiting."
          exit 1
        fi

        # Extract current version
        IFS='_' read -r _ version <<< "$latest_tag"
        IFS='.' read -r major minor patch <<< "${version#v}"

        # Increment patch version
        patch=$((patch + 1))

        # Create next tag
        next_tag="uat_v$major.$minor.$patch"

        echo "Next tag: $next_tag"
        echo "::set-output name=tag::$next_tag"

    - name: Create and push tag
      run: |
        next_tag=${{ steps.calculate-next-tag.outputs.tag }}
        git tag $next_tag
        echo $next_tag
        # git push origin $next_tag --force
