name: Manual Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to push the tag'
        required: true
        type: choice
        options:
          - main
          - feature

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get latest tag
      id: get-latest-tag
      run: |
        latest_tag=$(git tag --list 'uat_v*' | sort -V | tail -n 1)
        echo "Latest tag: $latest_tag"
        echo "::set-output name=tag::$latest_tag"
