name: Tag Dispatch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to push the tag'
        required: true
        type: choice
        options:
          - main
          - feature

  # push:
  #   # branches:
  #   #   - dev-test
  #       tags:
  #         - 'uat_v*'

jobs:
  tag-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.branch }}
        submodules: true

    
    - name: Get Latest Tag
      id: latest-tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Latest tag is: $latest_tag"
        echo "::set-output name=LATEST_TAG::$latest_tag"

    - name: Increment tag
      id: increment-tag
      run: |
        # Extract the tag from the output
        previous_tag="${{ steps.latest-tag.outputs.LATEST_TAG }}"
        
        # Increment the tag version 
        next_tag=$(echo "$previous_tag" | awk -F '.' '{$NF = $NF + 1;} 1' OFS='.')    
        echo "Next_tag: $next_tag"
        
    - name: Push new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag $Next_tag
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --tags

