name: Tag Verify

# on: 
#   workflow_dispatch:
#   push:
#     tags:
#       - 'uat_v*' 
on: 
  release: 
    types: 
      - created
      - released

jobs:
  tag-verify:
    runs-on: ubuntu-latest

    steps:

    - name: Get branch
      id: branch
      run: |
        echo "Execution is from main branch"
